#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Mar 27 16:34:51 GMT 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ab0e6e09636c4644886e0df5913b044d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot scatter_threshold_tb_behav xil_defaultlib.scatter_threshold_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto ab0e6e09636c4644886e0df5913b044d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot scatter_threshold_tb_behav xil_defaultlib.scatter_threshold_tb xil_defaultlib.glbl -log elaborate.log

