#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Mar 27 17:25:16 GMT 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim scatter_threshold_tb_behav -key {Behavioral:sim_1:Functional:scatter_threshold_tb} -tclbatch scatter_threshold_tb.tcl -log simulate.log"
xsim scatter_threshold_tb_behav -key {Behavioral:sim_1:Functional:scatter_threshold_tb} -tclbatch scatter_threshold_tb.tcl -log simulate.log

