accelerator: auto
accumulate_grad_batches: 1
action: test
batch_size: 128
config: null
dataset: jsc
disable_dataset_cache: false
github_ci: false
info: null
is_pretrained: false
is_to_auto_requeue: false
learning_rate: 1.0e-05
load_name: /content/mase/mase_output/jsc-ziyun-lab1_classification_jsc_2024-01-28/software/training_ckpts/best-v1.ckpt
load_type: pl
log_every_n_steps: 50
log_level: info
max_epochs: 20
max_steps: -1
max_token_len: 512
model: jsc-ziyun-lab1
num_devices: 1
num_nodes: 1
num_targets: 100
num_workers: 8
project: jsc-ziyun-lab1_classification_jsc_2024-01-28
project_dir: /content/mase/mase_output
quant_config: null
report_to: tensorboard
seed: 0
strategy: auto
target: xcu250-figd2104-2L-e
task: classification
to_debug: false
trainer_precision: 16-mixed
training_optimizer: adam
version: null
weight_decay: 0
