# no add
[default]
name = "msfp"
# *: MSFP12 weight: 8-bit exponent, 1-bit sign, 3 bit mantissa
# weight shape = [in_features, out_features]
weight_exponent_bias = 127
weight_exponent_width = 8
weight_width = 4
# *： MSFP12 activation
# weight shape = [in_features, out_features]
data_in_exponent_bias = 127
data_in_exponent_width = 8
data_in_width = 4
weight_block_size = [1, 16]
# data_in shape = [bz, in_features]
data_in_block_size = [1, 16]
# *: MSFP12 bias
bias_exponent_bias = 127
bias_exponent_width = 8
bias_width = 4
# bias shape = [1, output_features]
bias_block_size = [16]

[module_classes_to_modify.conv1d]
name = "default"

[module_classes_to_modify.conv2d]
name = "default"

[module_classes_to_modify.linear]
bias_block_size = [16]
bias_exponent_bias = 127
bias_exponent_width = 8
bias_width = 4
data_in_block_size = [1, 16]
data_in_exponent_bias = 127
data_in_exponent_width = 8
data_in_width = 4
name = "msfp"
weight_block_size = [1, 16]
weight_exponent_bias = 127
weight_exponent_width = 8
weight_width = 4

[module_classes_to_modify.relu]
data_in_block_size = [1, 16]
data_in_exponent_bias = 127
data_in_exponent_width = 8
data_in_width = 4
name = "msfp"

# Attention mechanism
[function_classes_to_modify.bmm]
data_in_block_size = [1, 16]
data_in_exponent_bias = 127
data_in_exponent_width = 8
data_in_width = 4
name = "msfp"
weight_block_size = [16, 1]
weight_exponent_bias = 127
weight_exponent_width = 8
weight_width = 4

[function_classes_to_modify.matmul]
data_in_block_size = [1, 16]
data_in_exponent_bias = 127
data_in_exponent_width = 8
data_in_width = 4
name = "msfp"
weight_block_size = [16, 1]
weight_exponent_bias = 127
weight_exponent_width = 8
weight_width = 4

[function_classes_to_modify.relu]
data_in_block_size = [1, 16]
data_in_exponent_bias = 127
data_in_exponent_width = 8
data_in_width = 4
name = "msfp"

[method_classes_to_modify.bmm]
data_in_block_size = [1, 16]
data_in_exponent_bias = 127
data_in_exponent_width = 8
data_in_width = 4
name = "msfp"
weight_block_size = [16, 1]
weight_exponent_bias = 127
weight_exponent_width = 8
weight_width = 4

[method_classes_to_modify.matmul]
data_in_block_size = [1, 16]
data_in_exponent_bias = 127
data_in_exponent_width = 8
data_in_width = 4
name = "msfp"
weight_block_size = [16, 1]
weight_exponent_bias = 127
weight_exponent_width = 8
weight_width = 4

[method_classes_to_modify.relu]
data_in_block_size = [1, 16]
data_in_exponent_bias = 127
data_in_exponent_width = 8
data_in_width = 4
name = "msfp"
