from .calculate_sparsity import add_pruning_metadata_analysis_pass
from .calculate_natural_sparsity import add_natural_sparsity_metadata_analysis_pass
from .hook_inspector import hook_inspection_analysis_pass
