wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711534686.696205
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 12
      - 35
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      - 71
      - 79
      - 83
      - 99
      - 103
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 12
      - 35
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      - 71
      - 79
      - 83
      - 99
      - 103
      3:
      - 23
      4: 3.10.6
      5: 0.16.3
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
