from .add import (
    add_block_fp,
    add_block_minifloat,
    add_integer,
    add_log,
    add_minifloat_denorm,
    add_minifloat_ieee,
)
from .matmul import (
    bmm_block_fp,
    bmm_block_minifloat,
    bmm_integer,
    bmm_log,
    bmm_minifloat_denorm,
    bmm_minifloat_ieee,
    matmul_block_fp,
    matmul_block_minifloat,
    matmul_integer,
    matmul_log,
    matmul_minifloat_denorm,
    matmul_minifloat_ieee,
)
from .mult import (
    mult_block_fp,
    mult_block_minifloat,
    mult_integer,
    mult_log,
    mult_minifloat_denorm,
    mult_minifloat_ieee,
)
from .relu import (
    relu_block_fp,
    relu_block_minifloat,
    relu_integer,
    relu_log,
    relu_minifloat_denorm,
    relu_minifloat_ieee,
)

quantized_func_map = {
    "add_block_minifloat": add_block_minifloat,
    "add_integer": add_integer,
    "add_log": add_log,
    "add_minifloat_ieee": add_minifloat_ieee,
    "add_minifloat_denorm": add_minifloat_denorm,
    "add_block_fp": add_block_fp,
    "sub_block_minifloat": add_block_minifloat,
    "sub_integer": add_integer,
    "sub_log": add_log,
    "sub_minifloat_ieee": add_minifloat_ieee,
    "sub_minifloat_denorm": add_minifloat_denorm,
    "sub_block_fp": add_block_fp,
    "mul_block_minifloat": mult_block_minifloat,
    "mul_integer": mult_integer,
    "mul_log": mult_log,
    "mul_minifloat_ieee": mult_minifloat_ieee,
    "mul_minifloat_denorm": mult_minifloat_denorm,
    "mul_block_fp": mult_block_fp,
    "bmm_block_minifloat": bmm_block_minifloat,
    "bmm_integer": bmm_integer,
    "bmm_log": bmm_log,
    "bmm_minifloat_ieee": bmm_minifloat_ieee,
    "bmm_minifloat_denorm": bmm_minifloat_denorm,
    "bmm_block_fp": bmm_block_fp,
    "matmul_block_minifloat": matmul_block_minifloat,
    "matmul_integer": matmul_integer,
    "matmul_log": matmul_log,
    "matmul_minifloat_ieee": matmul_minifloat_ieee,
    "matmul_minifloat_denorm": matmul_minifloat_denorm,
    "matmul_block_fp": matmul_block_fp,
}
