seed: 99
optimizer: re
dataset: cifar10
out_dir: run

search:
  checkpoint_freq: 5
  epochs: 150

  # GDAS
  tau_max: 10
  tau_min: 0.1

  # RE
  sample_size: 10
  population_size: 30
  
  # LS
  num_init: 10
  
  # BANANAS
  k: 10
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: mutation
  encoding_type: path
  num_arches_to_mutate: 2
  max_mutations: 1
  num_candidates: 100
  
  # GSparsity
  seed: 50
  grad_clip: 0
  threshold: 0.000001
  weight_decay: 60
  learning_rate: 0.001
  momentum: 0.8
  normalization: div
  normalization_exponent: 0.5
  batch_size: 64
  learning_rate_min: 0.0001
  epochs: 100
  warm_start_epochs: 0
  train_portion: 1.0
  data_size: 25000

