# random seed
seed: 0

# re, bananas, npenas, ls, rs
optimizer: re

# nasbench101, nasbench201, darts, nlp, transbench101, asr
search_space: nasbench201

# cifar10, cifar100, or ImageNet16-120 (only important for nasbench201)
dataset: cifar10

# output results to this directory
out_dir: run_boschcpu

# config id for the experiment
config_id: 0

# parameters for the optimizers
search:
  # for bohb
  budgets: 50000000
  checkpoint_freq: 1000
  fidelity: 108 
  
  # for all optimizers
  epochs: 10

  # for bananas and npenas, choose one predictor 
  # out of the 16 model-based predictors
  predictor_type: var_sparse_gp
  
  # number of initial architectures
  num_init: 10  

  # BANANAS
  k: 10
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: mutation
  encoding_type: adjacency_one_hot
  num_arches_to_mutate: 1 
  max_mutations: 1
  num_candidates: 50
  
  # jacov data loader
  batch_size: 256
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7
  
  # other params
  debug_predictor: False
  sample_size: 10
  population_size: 30

# copied directly from darts_defaults
evaluation:
  checkpoint_freq: 30
  batch_size: 96
  learning_rate: 0.025
  learning_rate_min: 0.00
  momentum: 0.9
  weight_decay: 0.0003
  epochs: 600
  warm_start_epochs: 0
  grad_clip: 5
  train_portion: 1.
  data_size: 50000

  cutout: True
  cutout_length: 16
  cutout_prob: 1.0
  drop_path_prob: 0.2
  auxiliary_weight: 0.4
