# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration for mase
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/kinetic64"
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.vm.synced_folder "..", "/workspace"
  config.vm.synced_folder "/scratch/shared/Xilinx", "/scratch/shared/Xilinx"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 16 
    vb.memory = "32768"
  end

  # # Provision script 
  # config.vm.provision "shell", inline: <<-SHELL
  #  bash /workspace/vagrant/vagrant.sh 
  # SHELL

end
