# random seed
seed: 0

# re, bananas, npenas, ls, rs
optimizer: re

# nasbench101, nasbench201, darts, nlp, 
# transbench101_micro, transbench101_macro, asr
search_space: nasbench201

# nasbench201 datasets: cifar10, cifar100, ImageNet16-120
# transbench101 datasets: class_scene, class_object, 
# jigsaw, room_layout, segmentsemantic, normal, autoencoder
dataset: cifar10

# output results to this directory
out_dir: run

# parameters for the optimizers
search:
  # for bohb
  budgets: 50000000
  checkpoint_freq: 1000
  fidelity: 108 
  
  # for all optimizers
  epochs: 100

  # for bananas and npenas, choose one predictor 
  # out of the 16 model-based predictors
  predictor_type: var_sparse_gp
  
  # number of initial architectures
  num_init: 10  

  # BANANAS
  k: 10
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: mutation
  encoding_type: adjacency_one_hot
  num_arches_to_mutate: 5
  max_mutations: 1
  num_candidates: 200
  
  # jacov data loader
  batch_size: 256
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7
  
  # other params
  debug_predictor: False
  sample_size: 10
  population_size: 30
