name: mase

channels:
  - symbiflow

dependencies:
  - python=3.10.6
  - pip
  - verible
  - pip:
    - lightning
    - transformers
    - diffusers
    - accelerate
    - toml
    - timm
    - pytorch-nlp
    - datasets
    - onnx
    - onnxruntime
    - optimum
    - black
    - GitPython
    - colorlog
    - cocotb[bus]==1.8.0
    - pytest
    - pytest-cov
    - pytest-xdist
    - pytest-sugar
    - pytest-html
    - pytest-profiling
    - ipython
    - ipdb
    - sentencepiece
    - einops
    - deepspeed
    - pybind11
    - tabulate
    - tensorboard
    - optuna
    - stable-baselines3
    - scikit-learn
    # LogicNets
    - h5py
    - pyyaml
    - numpy
    - pandas
    - wandb
    # NeRF
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - kornia
    - einops
    # doc
    - sphinx
    - sphinx-rtd-theme
