accelerator: gpu
accumulate_grad_batches: 1
action: train
batch_size: 256
config: /root/mase/machop/configs/examples/toy_uniform_tensorRT.toml
dataset: jsc
disable_dataset_cache: false
github_ci: false
info: null
is_pretrained: false
is_to_auto_requeue: false
learning_rate: 0.001
load_name: null
load_type: mz
log_every_n_steps: 50
log_level: info
max_epochs: 1
max_steps: -1
max_token_len: 512
model: jsc-tiny
no_warnings: false
num_devices: 1
num_nodes: 1
num_targets: 100
num_workers: 48
profile: false
project: jsc-tiny_classification_jsc_2024-03-03
project_dir: /root/mase/mase_output
quant_config: null
report_to: tensorboard
run_emit: false
seed: 0
skip_build: false
skip_test: false
strategy: auto
target: xcu250-figd2104-2L-e
task: classification
to_debug: false
trainer_precision: 16-mixed
training_optimizer: adam
version: null
weight_decay: 0
