#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Mar 26 13:22:23 GMT 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 5de405cf665f47c2aec811cd10ee818c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_scatter_threshold_behav xil_defaultlib.tb_scatter_threshold xil_defaultlib.glbl -log elaborate.log"
xelab -wto 5de405cf665f47c2aec811cd10ee818c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_scatter_threshold_behav xil_defaultlib.tb_scatter_threshold xil_defaultlib.glbl -log elaborate.log

