# basics
model = "jsc-toy"
dataset = "jsc"

max_epochs = 20
batch_size = 256
learning_rate = 1e-3
accelerator = "gpu"

[passes.tensorrt_quantize]
by = "type"
num_calibration_batches = 10
post_calibration_analysis = true

[passes.tensorrt_quantize.default.config]
quantize = true
calibrators = ["percentile", "mse", "entropy"]
percentiles = [99.0, 99.9, 99.99]
precision = 'FP16'

[passes.tensorrt_quantize.default.input]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt_quantize.default.weight]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt_analysis]
num_batches = 500
num_GPU_warmup_batches = 5
test = true