# basics
model = "jsc-toy"
dataset = "jsc"

load_name = "../mase_output/jsc-toy_cls_jsc-pre-trained/best.ckpt"
load_type = "pl"

max_epochs = 10
batch_size = 64
learning_rate = 1e-3
accelerator = "gpu"
task="cls"

[passes.tensorrt]
by = "type"
num_calibration_batches = 10
post_calibration_analysis = true

[passes.tensorrt.default.config]
quantize = true
calibrators = ["percentile", "mse", "entropy"]
percentiles = [99.0, 99.9, 99.99]
precision = 'fp16'

[passes.tensorrt.default.input]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt.default.weight]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt.runtime_analysis]
num_batches = 500
num_GPU_warmup_batches = 5
test = true