# basics
model = "vgg7"
dataset = "cifar10"

max_epochs = 10
batch_size = 64
learning_rate = 1e-3
accelerator = "gpu"
task="cls"

[transform]
style = "graph"

[passes.tensorrt]
by = "type"
num_calibration_batches = 10
post_calibration_analysis = true

[passes.tensorrt.default.config]
quantize = true
calibrators = ["percentile"]
percentiles = [99.99]
# calibrators = ["percentile", "mse", "entropy"]
# percentiles = [99.0, 99.9, 99.99]
precision = 'int8'

[passes.tensorrt.default.input]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt.default.weight]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt.feature_layers_0.config]
precision = 'fp16'

[passes.tensorrt.feature_layers_1.config]
precision = 'fp16'

[passes.tensorrt.feature_layers_2.config]
precision = 'int8'

[passes.tensorrt.feature_layers_3.config]
precision = 'int8'

[passes.tensorrt.fine_tune]
fine_tune = false

[passes.tensorrt.runtime_analysis]
num_batches = 500
num_GPU_warmup_batches = 5
test = true