# basics
model = "vgg7"
dataset = "cifar10"

max_epochs = 10
batch_size = 256
learning_rate = 1e-3
accelerator = "gpu"
task="cls"

[passes.tensorrt_quantize]
by = "type"
num_calibration_batches = 10
post_calibration_analysis = true

[passes.tensorrt_quantize.default.config]
quantize = true
calibrators = ["percentile"]
percentiles = [99.0, 99.9]
precision = 'INT8'

[passes.tensorrt_quantize.default.input]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt_quantize.default.weight]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt_quantize.linear.config]
quantize = false

[passes.tensorrt_quantize.conv2d.config]
quantize = true
precision = 'INT8'
calibrator = 'histogram'

[passes.tensorrt_quantize.conv2d.input]
quantize_axis = false

[passes.tensorrt_quantize.conv2d.weight]
quantize_axis = false

[passes.tensorrt_analysis]
num_batches = 500
num_GPU_warmup_batches = 5
test = true