webtalk_init -webtalk_dir /home/aw1223/new/mase/machop/mase_components/scatter/scatter_project/scatter_project.sim/sim_1/behav/xsim/xsim.dir/scatter_threshold_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 27 17:40:53 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210646553_1777496146_210698762_622" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "efc6c035-d3eb-40fd-9701-1ef404937e6c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ab0e6e09636c4644886e0df5913b044d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.9.2009 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1205.944 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "270.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.10_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124860_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1814398953 -regid "210646553_1777496146_210698762_622" -xml /home/aw1223/new/mase/machop/mase_components/scatter/scatter_project/scatter_project.sim/sim_1/behav/xsim/xsim.dir/scatter_threshold_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/aw1223/new/mase/machop/mase_components/scatter/scatter_project/scatter_project.sim/sim_1/behav/xsim/xsim.dir/scatter_threshold_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/aw1223/new/mase/machop/mase_components/scatter/scatter_project/scatter_project.sim/sim_1/behav/xsim/xsim.dir/scatter_threshold_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
