batch_size: 32
config_type: zc_example
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: cifar10
out_dir: run
predictor: fisher
search_space: nasbench201 #nasbench101  #nasbench301
test_size: 200
train_size: 400
optimizer: npenas
train_portion: 0.7
seed: 0

search:
  # for bohb
  seed: 0
  budgets: 50000000
  checkpoint_freq: 1000
  fidelity: 108 
  
  # for all optimizers
  epochs: 10

  # for bananas and npenas, choose one predictor 
  # out of the 16 model-based predictors
  predictor_type: var_sparse_gp
  
  # number of initial architectures
  num_init: 10  

  # NPENAS
  k: 10
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: mutation
  encoding_type: adjacency_one_hot
  num_arches_to_mutate: 1 
  max_mutations: 1
  num_candidates: 50
  
  # jacov data loader
  batch_size: 256
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7
  
  # other params
  debug_predictor: False
  sample_size: 10
  population_size: 30
  
  # zc parameters
  use_zc_api: False
  zc_ensemble: true
  zc_names:
    - params
    - flops
    - jacov
    - plain
    - grasp
    - snip
    - fisher
    - grad_norm
    - epe_nas
    - synflow
    - l2_norm
  zc_only: true