# basics
model = "toy_convnet"
dataset = "mnist"
task = "cls"

load_name = "../mase_output/toy-convnet_mnist_pre-trained/toy-convnet_mnist_0.955.ckpt"
load_type = "pl"

max_epochs = 10
batch_size = 64
learning_rate = 1e-3
accelerator = "gpu"

[passes.tensorrt]
by = "type"
num_calibration_batches = 10
post_calibration_analysis = true

[passes.tensorrt.default.config]
quantize = true
calibrators = ["percentile", "mse", "entropy"]
percentiles = [99.0, 99.9, 99.99]
precision = 'int8'

[passes.tensorrt.default.input]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt.default.weight]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt.runtime_analysis]
num_batches = 500
num_GPU_warmup_batches = 5
test = true