seed: 0
optimizer: bananas
search_space: nasbench201
dataset: cifar10
out_dir: run

search:
  checkpoint_freq: 1000
  epochs: 100
  fidelity: -1

  predictor_type: var_sparse_gp
  num_init: 10  
  k: 10

  # BANANAS
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: random_sampling
  encoding_type: adjacency_one_hot
  num_arches_to_mutate: 2
  max_mutations: 1
  num_candidates: 20
  
  # jacov data loader
  batch_size: 256
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7
  
  # other params
  debug_predictor: False
  sample_size: 10
  population_size: 30
