from .softermax import fixed_softermax

from .add import (
    add_block_fp,
    add_block_log,
    add_block_minifloat,
    add_integer,
    add_log,
    add_minifloat_denorm,
    add_minifloat_ieee,
    add_binary,
    add_ternary,
)
from .sub import (
    sub_block_fp,
    sub_block_log,
    sub_block_minifloat,
    sub_integer,
    sub_log,
    sub_minifloat_denorm,
    sub_minifloat_ieee,
    sub_binary,
    sub_ternary,
)
from .sub import (
    sub_block_fp,
    sub_block_log,
    sub_block_minifloat,
    sub_integer,
    sub_log,
    sub_minifloat_denorm,
    sub_minifloat_ieee,
    sub_binary,
)
from .matmul import (
    bmm_block_fp,
    bmm_block_log,
    bmm_block_minifloat,
    bmm_integer,
    bmm_log,
    bmm_minifloat_denorm,
    bmm_minifloat_ieee,
    bmm_binary,
    bmm_ternary,
    matmul_block_fp,
    matmul_block_log,
    matmul_block_minifloat,
    matmul_integer,
    matmul_log,
    matmul_minifloat_denorm,
    matmul_minifloat_ieee,
    matmul_binary,
    matmul_ternary,
)
from .mult import (
    mult_block_fp,
    mult_block_log,
    mult_block_minifloat,
    mult_integer,
    mult_log,
    mult_minifloat_denorm,
    mult_minifloat_ieee,
    mult_binary,
    mult_ternary,
)
from .relu import (
    relu_block_fp,
    relu_block_log,
    relu_block_minifloat,
    relu_integer,
    relu_log,
    relu_minifloat_denorm,
    relu_minifloat_ieee,
    relu_binary,
    relu_ternary,
)

from .selu import (
    selu_block_fp,
    selu_block_log,
    selu_block_minifloat,
    selu_integer,
    selu_log,
    selu_minifloat_denorm,
    selu_minifloat_ieee,
    selu_binary,
    selu_ternary,
)

from .tanh import (
    tanh_block_fp,
    tanh_block_log,
    tanh_block_minifloat,
    tanh_integer,
    tanh_log,
    tanh_minifloat_denorm,
    tanh_minifloat_ieee,
    tanh_binary,
    tanh_ternary,
)

from .gelu import (
    gelu_block_fp,
    gelu_block_log,
    gelu_block_minifloat,
    gelu_integer,
    gelu_log,
    gelu_minifloat_denorm,
    gelu_minifloat_ieee,
    gelu_binary,
    gelu_ternary,
)

from .softsign import (
    softsign_block_fp,
    softsign_block_log,
    softsign_block_minifloat,
    softsign_integer,
    softsign_log,
    softsign_minifloat_denorm,
    softsign_minifloat_ieee,
    softsign_binary,
    softsign_ternary,
)

from .softplus import (
    softplus_block_fp,
    softplus_block_log,
    softplus_block_minifloat,
    softplus_integer,
    softplus_log,
    softplus_minifloat_denorm,
    softplus_minifloat_ieee,
    softplus_binary,
    softplus_ternary,
)

quantized_func_map = {
    "add_block_minifloat": add_block_minifloat,
    "add_integer": add_integer,
    "add_fixed": add_integer,
    "add_log": add_log,
    "add_minifloat_ieee": add_minifloat_ieee,
    "add_minifloat_denorm": add_minifloat_denorm,
    "add_block_fp": add_block_fp,
    "add_block_log": add_block_log,
    "add_binary": add_binary,
    "add_ternary": add_ternary,
    "sub_block_minifloat": sub_block_minifloat,
    "sub_integer": sub_integer,
    "sub_fixed": sub_integer,
    "sub_log": sub_log,
    "sub_minifloat_ieee": sub_minifloat_ieee,
    "sub_minifloat_denorm": sub_minifloat_denorm,
    "sub_block_fp": sub_block_fp,
    "sub_block_log": sub_block_log,
    "sub_binary": sub_binary,
    "sub_ternary": sub_ternary,
    "mul_block_minifloat": mult_block_minifloat,
    "mul_integer": mult_integer,
    "mul_fixed": mult_integer,
    "mul_log": mult_log,
    "mul_minifloat_ieee": mult_minifloat_ieee,
    "mul_minifloat_denorm": mult_minifloat_denorm,
    "mul_block_fp": mult_block_fp,
    "mul_block_log": mult_block_log,
    "mul_binary": mult_binary,
    "mul_ternary": mult_ternary,
    "bmm_block_minifloat": bmm_block_minifloat,
    "bmm_integer": bmm_integer,
    "bmm_fixed": bmm_integer,
    "bmm_log": bmm_log,
    "bmm_minifloat_ieee": bmm_minifloat_ieee,
    "bmm_minifloat_denorm": bmm_minifloat_denorm,
    "bmm_block_fp": bmm_block_fp,
    "bmm_block_log": bmm_block_log,
    "bmm_binary": bmm_binary,
    "bmm_ternary": bmm_ternary,
    "matmul_block_minifloat": matmul_block_minifloat,
    "matmul_integer": matmul_integer,
    "matmul_fixed": matmul_integer,
    "matmul_log": matmul_log,
    "matmul_minifloat_ieee": matmul_minifloat_ieee,
    "matmul_minifloat_denorm": matmul_minifloat_denorm,
    "matmul_block_fp": matmul_block_fp,
    "matmul_block_log": matmul_block_log,
    "matmul_binary": matmul_binary,
    "matmul_ternary": matmul_ternary,
    "relu_block_minifloat": relu_block_minifloat,
    "relu_integer": relu_integer,
    "relu_fixed": relu_integer,
    "relu_log": relu_log,
    "relu_minifloat_ieee": relu_minifloat_ieee,
    "relu_minifloat_denorm": relu_minifloat_denorm,
    "relu_block_fp": relu_block_fp,
    "relu_block_log": relu_block_log,
    "relu_binary": relu_binary,
    "relu_ternary": relu_ternary,
    "selu_block_minifloat": selu_block_minifloat,
    "selu_integer": selu_integer,
    "selu_fixed": selu_integer,
    "selu_log": selu_log,
    "selu_minifloat_ieee": selu_minifloat_ieee,
    "selu_minifloat_denorm": selu_minifloat_denorm,
    "selu_block_fp": selu_block_fp,
    "selu_block_log": selu_block_log,
    "selu_binary": selu_binary,
    "selu_ternary": selu_ternary,
    "tanh_block_minifloat": tanh_block_minifloat,
    "tanh_integer": tanh_integer,
    "tanh_fixed": tanh_integer,
    "tanh_log": tanh_log,
    "tanh_minifloat_ieee": tanh_minifloat_ieee,
    "tanh_minifloat_denorm": tanh_minifloat_denorm,
    "tanh_block_fp": tanh_block_fp,
    "tanh_block_log": tanh_block_log,
    "tanh_binary": tanh_binary,
    "tanh_ternary": tanh_ternary,
    "gelu_block_minifloat": gelu_block_minifloat,
    "gelu_integer": gelu_integer,
    "gelu_fixed": gelu_integer,
    "gelu_log": gelu_log,
    "gelu_minifloat_ieee": gelu_minifloat_ieee,
    "gelu_minifloat_denorm": gelu_minifloat_denorm,
    "gelu_block_fp": gelu_block_fp,
    "gelu_block_log": gelu_block_log,
    "gelu_binary": gelu_binary,
    "gelu_ternary": gelu_ternary,
    "softsign_block_minifloat": softsign_block_minifloat,
    "softsign_integer": softsign_integer,
    "softsign_fixed": softsign_integer,
    "softsign_log": softsign_log,
    "softsign_minifloat_ieee": softsign_minifloat_ieee,
    "softsign_minifloat_denorm": softsign_minifloat_denorm,
    "softsign_block_fp": softsign_block_fp,
    "softsign_block_log": softsign_block_log,
    "softsign_binary": softsign_binary,
    "softsign_ternary": softsign_ternary,
    "softplus_block_minifloat": softplus_block_minifloat,
    "softplus_integer": softplus_integer,
    "softplus_fixed": softplus_integer,
    "softplus_log": softplus_log,
    "softplus_minifloat_ieee": softplus_minifloat_ieee,
    "softplus_minifloat_denorm": softplus_minifloat_denorm,
    "softplus_block_fp": softplus_block_fp,
    "softplus_block_log": softplus_block_log,
    "softplus_binary": softplus_binary,
    "softplus_ternary": softplus_ternary,
}
