/*
Module      : matrix_unflatten
Description : This module is a purely combinatorial block which unflattens a 1D
              bit vector generated by the "matrix_flatten" module.
*/

`timescale 1ns / 1ps

module matrix_unflatten #(
    parameter DATA_WIDTH = 32,
    parameter DIM0       = 4,
    parameter DIM1       = 4
) (
    input  logic [DATA_WIDTH*DIM0*DIM1-1:0] data_in,
    output logic [          DATA_WIDTH-1:0] data_out[DIM0*DIM1-1:0]
);

  for (genvar i = 0; i < DIM0 * DIM1; i++) begin
    assign data_out[i] = data_in[(i+1)*DATA_WIDTH-1:i*DATA_WIDTH];
  end

endmodule
