# basics
model = "jsc-toy"
dataset = "jsc"
task = "cls"

max_epochs = 10
batch_size = 256
accelerator = "gpu"
learning_rate = 1e3

[passes.onnxruntime.default.config]
quantize = true
num_calibration_batches = 200
quantize_types = ['static', 'dynamic']
precision = 'int8'

[passes.onnxruntime.runtime_analysis]
num_batches = 500
num_GPU_warmup_batches = 5
test = true
