# basics
model = "mobilenetv3_small"
dataset = "mnist"
task = "cls"
# pretrained = true

load_name = "../mase_output/mobilenetv3-small_pre-trained_mnist/mobilenetv3_small_mnist_0.997.ckpt"
load_type = "pl"

max_epochs = 10
batch_size = 64
accelerator = "gpu"
learning_rate = 1e-3

[passes.onnxruntime.default.config]
quantize = true
num_calibration_batches = 200
quantize_types = ['static', 'dynamic', 'auto']
precision = 'uint8'

[passes.onnxruntime.runtime_analysis]
original_graph_analysis = true
optimized_graph_analysis = true
quantized_graph_analysis = true
num_batches = 100
num_GPU_warmup_batches = 5
test = true
