# basics
model = "toy_convnet"
dataset = "mnist"
task = "cls"

load_name = "../mase_output/toy-convnet_mnist_pre-trained/toy-convnet_mnist_0.955.ckpt"
load_type = "pl"

max_epochs = 10
batch_size = 64
accelerator = "gpu"
learning_rate = 1e-3

[passes.onnxruntime.runtime_analysis]
num_batches = 100
num_GPU_warmup_batches = 5
test = true