# basics
model = "vgg7"
dataset = "cifar10"

# max_epochs = 10
batch_size = 16
accelerator = "gpu"
# learning_rate = 1e-3
# project = "jsc-tiny"
load_name = "../TensorRTDev/vgg7-test-accu-0.9332.ckpt"
load_type = "pl"


[passes.onnxruntime]
do_test = "after" # tests original PyTorch checkpoint performance if "before", post-conversion performance if "after", both if "both"; no test if "NA"
do_train = false

# [passes.tensorrt_analysis]
# num_batches = 500
# num_GPU_warmup_batches = 5
# test = true