# basics
model = "vgg7"
dataset = "cifar10"
task = "cls"

max_epochs = 10
batch_size = 16
accelerator = "gpu"
learning_rate = 1e-3

[passes.onnxruntime.default.config]
quantize = true
quantize_types = ['static', 'dynamic']
precision = 'int8'

[passes.onnxruntime.runtime_analysis]
original_graph_analysis = true
optimized_graph_analysis = true
quantized_graph_analysis = true
num_batches = 100
num_GPU_warmup_batches = 5
test = true