# basics
model = "vgg7"
dataset = "cifar10"
task = "cls"

max_epochs = 300
batch_size = 1024
learning_rate = 1e-2
accelerator = "cpu"
project = "rl_search"
seed = 42
log_every_n_steps = 5
load_name = "/mnt/c/workplace/projects/ADLS/mase/txl_workplace/test-accu-0.9332.ckpt"
load_type = "pl"

[passes.quantize]
by = "type"
[passes.quantize.default.config]
name = "NA"
[passes.quantize.linear.config]
name = "integer"
"data_in_width" = 8
"data_in_frac_width" = 4
"weight_width" = 8
"weight_frac_width" = 4
"bias_width" = 8
"bias_frac_width" = 4

[search.search_space]
name = "graph/quantize/mixed_precision_ptq"

[search.search_space.setup]
by = "type"

[search.search_space.seed.default.config]
# the only choice "NA" is used to indicate that layers are not quantized by default
name = ["NA"]

[search.search_space.seed.linear.config]
# if search.search_space.setup.by = "type", this seed will be used to quantize all torch.nn.Linear/ F.linear
name = ["integer"]
data_in_width = [2, 3, 4, 5, 6, 7, 8]
data_in_frac_width = ["NA"] # "NA" means data_in_frac_width = data_in_width // 2
weight_width = [2, 3, 4, 5, 6, 7, 8]
weight_frac_width = ["NA"]
bias_width = [2, 3, 4, 5, 6, 7, 8]
bias_frac_width = ["NA"]

[search.search_space.seed.conv2d.config]
name = ["integer"]
data_in_width = [2, 3, 4, 5, 6, 7, 8]
data_in_frac_width = ["NA"] # "NA" means data_in_frac_width = data_in_width // 2
weight_width = [2, 3, 4, 5, 6, 7, 8]
weight_frac_width = ["NA"]
bias_width = [2, 3, 4, 5, 6, 7, 8]
bias_frac_width = ["NA"]

#[search.search_space.seed.relu.config]
#name = ["integer"]
#data_in_width = [2, 3, 4, 5, 6, 7, 8]
#data_in_frac_width = ["NA"] # "NA" means data_in_frac_width = data_in_width // 2

[search.strategy]
name = "rl"
eval_mode = true

[search.strategy.sw_runner.basic_evaluation]
data_loader = "val_dataloader"
num_samples = 1024

[search.strategy.hw_runner.average_bitwidth]
compare_to = 32 # compare to FP32

[search.strategy.setup]
device = "cpu"
total_timesteps = 270
algorithm = "a2c"
env = "MixedPrecisionEnv"

[search.strategy.metrics]
accuracy.scale = 10.0
average_bitwidth.scale = -0.1
