# basics
model = "jsc-tiny"
dataset = "jsc"

max_epochs = 10
batch_size = 256
learning_rate = 1e-3
accelerator = "gpu"

[passes.tensorrt-calibrate]
by = "type"
calibrator = ["percentile", "max", "mse", "entropy"]
percentiles = [99]
report = true

[passes.tensorrt-calibrate.linear.config]
quantize = true

[passes.tensorrt-calibrate.linear.input]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt-calibrate.linear.weight]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt-calibrate.default.config]
quantize = true

[passes.tensorrt-calibrate.default.config.input]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt-calibrate.default.config.weight]
calibrator = 'histogram'
quantize_axis = false

[passes.tensorrt-quantize]
by = "type"

[passes.tensorrt-quantize.default.config]
name = "integer"
data_in_width = 8
data_in_frac_width = 4
weight_width = 8
weight_frac_width = 9
bias_width = 8
bias_frac_width = 9

[passes.tensorrt-analysis]
analysis = ['latency', 'accuracy', 'gpu_power', 'F1_score', 'recall', 'precision']
num_batches = 20
num_GPU_warmup_iterations = 5