# basics
model = "vgg7"
dataset = "cifar10"
task = "cls"
 
max_epochs = 5512
batch_size = 512
learning_rate = 1e-3
accelerator = "gpu"
project = "vgg7_tpe"
seed = 42
log_every_n_steps = 5
load_name = "test-accu-0.9332.ckpt"
load_type = "pl"
 
[search.search_space]
name = "graph/quantize/mixed_precision_ptq"
 
[search.search_space.setup]
by = "name"
 
[search.search_space.seed.default.config]
name = ["integer"]
data_in_width = [32, 16]
data_in_frac_width = [2, 4, 8, 10, 12, 16]
weight_width = [32, 16]
weight_frac_width = [2, 4, 8, 10, 12, 16]
bias_width = [32, 16]
bias_frac_width = [2, 4, 8, 10, 12, 16]
 
[search.strategy]
name = "optuna"
eval_mode = true
 
[search.strategy.sw_runner.basic_evaluation]
data_loader = "val_dataloader"
num_samples = 512
 
[search.strategy.hw_runner.average_bitwidth]
compare_to = 32 # compare to FP32
 
[search.strategy.setup]
n_jobs = 1
n_trials = 20
timeout = 20000
sampler = "tpe"
#sampler = "brute-force"
# sum_scaled_metrics = true # single objective
# direction = "maximize"
sum_scaled_metrics = false # multi objective
 
[search.strategy.metrics]
# loss.scale = 1.0
# loss.direction = "minimize"
accuracy.scale = 1.0
accuracy.direction = "maximize"
average_bitwidth.scale = 0.2
average_bitwidth.direction = "minimize"