# basics
model = "jsc-tiny"
dataset = "jsc"

[passes.tensorrt-quantize]
by = "type"
report = true

[passes.tensorrt-quantize.default.config]
name = "integer"
data_in_width = 8
data_in_frac_width = 4
weight_width = 8
weight_frac_width = 9
bias_width = 8
bias_frac_width = 9