# basics
model = "jsc-tiny"
dataset = "jsc"
task = "cls"

max_epochs = 10
batch_size = 512
learning_rate = 1e-2
accelerator = "gpu"
project = "jsc-tiny"
seed = 42
log_every_n_steps = 5
load_name = "mase_output/jsc-tiny_classification_jsc_2024-01-31/software/training_ckpts/best-v3.ckpt"
load_type = "pl"

[search.search_space]
name = "graph/quantize/mixed_precision_ptq"

[search.search_space.setup]
by = "name"

[search.search_space.seed.default.config]
name = ["integer"]
data_in_width = [4, 8]
data_in_frac_width = [3, 4, 5, 6, 7, 8, 9]
weight_width = [2, 4, 8]
weight_frac_width = [3, 4, 5, 6, 7, 8, 9]
bias_width = [2, 4, 8]
bias_frac_width = [3, 4, 5, 6, 7, 8, 9]

[search.strategy]
name = "rl"
algorithm = 'ppo'
env = 'mixed_precision_hi_lo'
num_episodes = 1 
device = 'cuda'
total_timesteps = 100000
save_name = 'tmp_rl'
#load_name = 'logs/best_model/best_model.zip'

[search.strategy.setup]
# sum_scaled_metrics = true # single objective
# direction = "maximize"
sum_scaled_metrics = false # multi objective

[search.strategy.sw_runner.basic_evaluation]
data_loader = "val_dataloader"
num_samples = 512

[search.strategy.hw_runner.average_bitwidth]
compare_to = 32 # compare to FP32

[search.strategy.metrics]
# loss.scale = 1.0
# loss.direction = "minimize"
accuracy.scale = 1.0
accuracy.direction = "maximize"
average_bitwidth.scale = 0.2
average_bitwidth.direction = "minimize"