# basics
model = "jsc-tiny"
dataset = "jsc"

max_epochs = 1
batch_size = 256
learning_rate = 1e-3
accelerator = "gpu"

[passes.tensorrt-calibrate]
by = "type"
calibrator = "percentile"
percentiles = [99]

# calibrator = "max"


report = true


[passes.tensorrt-quantize]
by = "type"

[passes.tensorrt-quantize.default.config]
name = "integer"
data_in_width = 8
data_in_frac_width = 4
weight_width = 8
weight_frac_width = 9
bias_width = 8
bias_frac_width = 9