# basics
model = "vgg7"
dataset = "cifar10"
task = "cls"

max_epochs = 5512
batch_size = 512
learning_rate = 1e-3
accelerator = "gpu"
project = "vgg7"
seed = 42
log_every_n_steps = 5
load_name = "/home/lch121600/ADLSlab/mase/mase_output/vgg7_classification_cifar10_2024-02-21/test-accu-0.9332.ckpt"
load_type = "pl"

[passes.quantize]
by = "type"
[passes.quantize.default.config]
name = "NA"
[passes.quantize.linear.config]
name = "integer"
"data_in_width" = 8
"data_in_frac_width" = 4
"weight_width" = 8
"weight_frac_width" = 4
"bias_width" = 8
"bias_frac_width" = 4

[passes.quantize.conv2d.config]
name = "integer"
"data_in_width" = 8
"data_in_frac_width" = 4
"weight_width" = 8
"weight_frac_width" = 4
"bias_width" = 8
"bias_frac_width" = 4

[passes.quantize.batch_norm2d.config]
name = "integer"
"data_in_width" = 8
"data_in_frac_width" = 4
"weight_width" = 8
"weight_frac_width" = 4
"bias_width" = 8
"bias_frac_width" = 4



[search.search_space]
name = "graph/quantize/mixed_precision_ptq"

[search.search_space.setup]
by = "type"

[search.search_space.seed.default.config]
# the only choice "NA" is used to indicate that layers are not quantized by default
name = ["NA"]

[search.search_space.seed.linear.config]
# if search.search_space.setup.by = "type", this seed will be used to quantize all torch.nn.Linear/ F.linear
name = ["integer"]
data_in_width = [4, 8, 16, 32]
data_in_frac_width = ["NA"] # "NA" means data_in_frac_width = data_in_width // 2
weight_width = [4, 8, 16, 32]
weight_frac_width = ["NA"]
bias_width = [4, 8, 16, 32]
bias_frac_width = ["NA"]

[search.search_space.seed.conv2d.config]	
# if search.search_space.setup.by = "type", this seed will be used to quantize all torch.nn.Linear/ F.linear
name = ["integer"]
data_in_width = [4, 8, 16, 32]
data_in_frac_width = ["NA"] # "NA" means data_in_frac_width = data_in_width // 2
weight_width = [4, 8, 16, 32]
weight_frac_width = ["NA"]
bias_width = [4, 8, 16, 32]
bias_frac_width = ["NA"]

# [search.search_space.seed.batch_norm2d.config]
# if search.search_space.setup.by = "type", this seed will be used to quantize all torch.nn.Linear/ F.linear
# name = ["integer"]
# data_in_width = [ 16, 8, 4]
# data_in_frac_width = ["NA"] # "NA" means data_in_frac_width = data_in_width // 2
# weight_width = [2, 4, 8]
# weight_frac_width = ["NA"]
# bias_width = [2, 4, 8]
# bias_frac_width = ["NA"]


[search.strategy]
name = "optuna"
eval_mode = true

[search.strategy.sw_runner.basic_evaluation]
data_loader = "val_dataloader"
num_samples = 512

[search.strategy.hw_runner.average_bitwidth]
compare_to = 32 # compare to FP32

[search.strategy.setup]
n_jobs = 1
n_trials = 20
timeout = 20000
sampler = "tpe"
#sampler = "brute-force"
sum_scaled_metrics = false # multi objective
#direction = "maximize"
#sum_scaled_metrics = true # single objective

[search.strategy.metrics]
# loss.scale = 1.0
# loss.direction = "minimize"
accuracy.scale = 1.0
accuracy.direction = "maximize"
average_bitwidth.scale = 0.2
average_bitwidth.direction = "minimize"
