# basics
model = "vgg7"
dataset = "cifar10"

max_epochs = 10
batch_size = 256
learning_rate = 1e-3
accelerator = "gpu"

[passes.tensorrt_quantize]
by = "type"
calibrator = ["percentile", "mse", "entropy"] # max can only be used if histogram is not set
num_calibration_batches = 10
percentiles = [99]
report = true

[passes.tensorrt_quantize.linear.config]
calibrator = 'histogram'
quantize = true
precision = 'INT8'

[passes.tensorrt_quantize.linear.input]
quantize_axis = false

[passes.tensorrt_quantize.linear.weight]
quantize_axis = false 

[passes.tensorrt_quantize.conv2d.config]
quantize = true
calibrator = 'histogram'
precision = 'INT8'

[passes.tensorrt_quantize.conv2d.input]
quantize_axis = false

[passes.tensorrt_quantize.conv2d.weight]
quantize_axis = false

[passes.tensorrt_quantize.default.config]
quantize = true
calibrator = 'histogram'
precision = 'FP16' # 'INT8'

[passes.tensorrt_quantize.default.config.input]
quantize_axis = false

[passes.tensorrt_quantize.default.config.weight]
quantize_axis = false

[passes.tensorrt_fine_tune]
qat_epochs = 10

[passes.tensorrt_analysis]
num_batches = 20
num_GPU_warmup_batches = 5