# basics
model = "jsc-tiny"
dataset = "jsc"
task = "cls"

max_epochs = 5
batch_size = 512
learning_rate = 1e-2
accelerator = "cpu"
project = "zero_cost_proxy_test"
seed = 42
log_every_n_steps = 5
load_name = "../mase_output/jsc_tiny_search_test_1/software/training_ckpts/best.ckpt"
load_type = "pl"

[search.search_space]
name = "graph/zero_cost_proxy"

[search.search_space.setup]
by = "name"

[search.search_space.zc]
seed = 2
benchmark = 'nasbench201'
dataset = 'cifar10'
calculate_proxy = false
ensemble_model = 'nonlinear'
loss_fn = 'mae'
optimizer = 'adam'
batch_size = 4
learning_rate = 0.02
epochs = 30
num_archs_train = 1000
num_archs_test = 2000
zc_proxies = ['epe_nas', 'fisher', 'grad_norm', 'grasp', 'jacov', 'l2_norm', 'nwot', 'plain', 'snip', 'synflow', 'zen', 'flops', 'params']

[search.strategy]
name = "naslib"

[search.strategy.sw_runner.basic_evaluation]
data_loader = "val_dataloader"
num_samples = 512

[search.strategy.hw_runner.average_bitwidth]
compare_to = 32

[search.strategy.setup]
n_jobs = 4
n_trials = 100
timeout = 20000
sampler = "tpe"
direction = "minimize"
weight_lower_limit = 0
weight_upper_limit = 30

# [search.strategy.metrics]
# # loss.scale = 1.0
# # loss.direction = "minimize"
# accuracy.scale = 1.0
# accuracy.direction = "maximize"
# average_bitwidth.scale = 0.2
# average_bitwidth.direction = "minimize"
