#basics

model = "resnet18"
dataset = "cifar10"

# training
training_optimizer = "adamw"
learning_rate = 1e-5
max_epochs = 10
batch_size = 32
# torch lightning
task = "classification"
num_workers = 0
num_devices = 1
accelerator = "cpu"

[passes.quantize]
by = "type"
report = true

[passes.quantize.default.config]
name = "ternary"
data_in_scaling_factor = false
data_in_width = 2
weight_scaling_factor = false
weight_width = 2
bias_scaling_factor = false
bias_width = 2
