[strategy]
name = 'hyperopt'

[strategy_config]
algorithm = 'tpe'
max_evals = 3
output_file = 'hyperopt_results.toml'

[search_space]
bias_frac_width = [1, 2, 4, 8, 16, 32]
bias_width = [1, 2, 4, 8, 16, 32]
data_in_frac_width = [1, 2, 4, 8, 16, 32]
data_in_width = [1, 2, 4, 8, 16, 32]
name = ['integer']
weight_frac_width = [1, 2, 4, 8, 16, 32]
weight_width = [1, 2, 4, 8, 16, 32]

[search_data]
# dataloader = 'train_dataloader'
num_batches = 8
