by = "name"
[default]
name = "integer"
data_in_width = 8
data_in_frac_width = 4
weight_width = 8
weight_frac_width = 4
bias_width = 8
bias_frac_width = 4

[model_layer_0.attention.query]
name = "minifloat_denorm"
bias_exponent_bias = 7
bias_exponent_width = 4
bias_width = 8
data_in_exponent_bias = 7
data_in_exponent_width = 4
data_in_width = 8
weight_exponent_bias = 7
weight_exponent_width = 4
weight_width = 8
