name: Python Format

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  python_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Black to format Python files
        if: ${{ always() }}
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -e '\.py$' || echo -n)
          if [[ ! -z $files ]]; then
            for f in $files
            do
              if [[ -f $f ]]; then
                python3 -m black --quiet $f
              fi
            done
            echo "Python files formatted successfully"
          else
            echo "No Python files found to format"
          fi
