name: Python Format

on:
  push:
    branches:
      - main
      - lab1_gs1123

jobs:
  python_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: List Python files before formatting
        run: |
          cd machop || exit 1  # Exit if unable to navigate to machop directory
          find . -type f -name "*.py" > before.txt || true  # Redirect output to before.txt or ignore error if file already exists

      - name: Run Black to format Python files
        if: ${{ always() }}
        run: |
          cd machop || exit 1  # Exit if unable to navigate to machop directory
          find . -type f -name "*.py" -exec python -m black --quiet {} \;

      - name: List Python files after formatting
        run: |
          cd machop || exit 1  # Exit if unable to navigate to machop directory
          find . -type f -name "*.py" > after.txt || true  # Redirect output to after.txt or ignore error if file already exists

      - name: Print changed files
        run: |
          diff before.txt after.txt | grep "^> " | cut -c 3-

      - name: Cleanup
        run: |
          rm before.txt after.txt
