name: Python Format

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  python_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Create before.txt
        run: |
          cd machop  # Adjust the path accordingly
          touch before.txt

      - name: List Python files before formatting
        run: |
          cd machop  # Adjust the path accordingly
          find . -type f -name "*.py" > before.txt || echo "No Python files found"
          cat before.txt

      - name: Run Black to format Python files
        if: ${{ always() }}
        run: |
          cd machop  # Adjust the path accordingly
          find . -type f -name "*.py" -exec python -m black --quiet {} \;

      - name: List Python files after formatting
        run: |
          cd machop  # Adjust the path accordingly
          find . -type f -name "*.py" > after.txt || echo "No Python files found"
          cat after.txt

      - name: Print changed files
        run: |
          diff before.txt after.txt | grep "^> " | cut -c 3- || echo "No changes detected"

      - name: Cleanup
        run: |
          rm before.txt after.txt || true  # Ignore errors if files don't exist
